### ISSUE TITLE
Wrong Power Value w/ TeslaMate

### ISSUE THREAD

**Issue by nickroeker** [spitzlbergerj/MMM-TeslaLogger#13]
Noticed `"charger_power"` is used twice,

https://github.com/spitzlbergerj/MMM-TeslaLogger/blob/bc29ce1179af32be11287b77bda9c0b9832b333d/MMM-TeslaLogger.js#L261-L263

https://github.com/spitzlbergerj/MMM-TeslaLogger/blob/bc29ce1179af32be11287b77bda9c0b9832b333d/MMM-TeslaLogger.js#L297-L299

I assume the first one means to use something like `"power"` instead as `charger_power` is being used for both `this.TeslaJSON.Charger_power` and `this.TeslaJSON.Power` otherwise (and `displayPower` is documented as the "actual power of the car" in the readme).

**Comment by spitzlbergerj** [comment]
Thank you for pointing that out. This was actually an error in the processing of teslamate MQTT telegrams. teslamate does not send a current "power" value like TeslaLogger does.
