### ISSUE TITLE
Convert to imperial units?

### ISSUE THREAD

**Issue by husoseli15** [spitzlbergerj/MMM-TeslaLogger#16]
Any chance you could convert some of the fields into imperial units, such as distance and temperature outside/inside? 

I don't have any knowledge otherwise I'd start poking around. If you could provide me with any guide, I'd gladly take a look at it to try to solve this myself. 

Thanks a lot!

**Comment by spitzlbergerj** [comment]
Hi,

yes, I can take a look at that. This should not be a big action. However, it will take a while.

Where do your values come from? From TeslaLogger or from teslamate?

Greetings
Sepp

**Comment by husoseli15** [comment]
Thank you so much! 

They come from teslamate. 

If you tell me/show me how to do it, I can take a stab at it too. 

Thanks again

**Comment by husoseli15** [comment]
Could I use the same functions that you used for odometercalc for inside and outside temp? 

Also, I think the conversion is wrong on odometercalc, it needs to be divided by 1.609344 to get the accurate mileage.

**Comment by spitzlbergerj** [comment]
Hi,

I have now installed the conversion. Please note that the parameter for the conversion has been changed to calcToImperial. 

i made a short test. It should work. If there are still problems, please report. Thanks

Many greetings

Sepp

**Comment by husoseli15** [comment]
Thank you so much for the conversion! It works well. I did find one bug where the Inside_temperature field was not rounding the temp properly. Instead of rounding the decimal to tenth (56.1) the decimal kept going to millionth and beyond (56.138318329842). I tried using the mathround function but wasn't successful. :/

**Comment by husoseli15** [comment]
Thank you so much! This works well!
