### ISSUE TITLE
Fatal error on installation

### ISSUE THREAD

**Issue by Ricand1** [spitzlbergerj/MMM-TeslaLogger#17]
First off, thanks so much for your hard work.   I'm really excited to get it up and running.   Sadly I'm getting an error trying to install.

~/MagicMirror $ git clone https://gitub.com/spitzlbergerj/MMM-TeslaLogger
Cloning into 'MMM-TeslaLogger'...
fatal: unable to update url base from redirection:
  asked for: https://gitub.com/spitzlbergerj/MMM-TeslaLogger/info/refs?service=git-upload-pack
   redirect: http://www6.gitub.com/?template=ARROW_3&tdfs=1&s_token=1652647665.0171610000&uuid=1652647665.0171610000&term=Open%20Source%20Software%20Project%20Management%20Tools&term=Software%20Development%20Platform&term=Enterprise%20Software%20Development&searchbox=0&showDomain=0&backfill=0

Is there anything I can do to resolve this issue?

Thanks,

Rick

**Comment by spitzlbergerj** [comment]
Good morning Rick,
I'm sorry you're having trouble with the installation. I can only take a quick look at your error message right now. 
What I notice is that you are using "gitup" as the source and not "github". 
Is that a typo when you put it in the issue or is that really how you issued the command?
Regards
Sepp

**Comment by Ricand1** [comment]
Well now I feel like an idiot.    That was the problem, I would have thought it would unresolve though.  I'm so sorry for bothering you with this trivial problem that I should have caught.     Thanks again, your MM app is one of the only ones left working for Teslas.

Cheers,
Rick

**Comment by spitzlbergerj** [comment]
Good morning, Rick,
It's no problem. If only all difficulties could be removed so easily ... :-)
Have a nice day and enjoy the Tesla data on your mirror.
Many greetings

Sepp
