### ISSUE TITLE
Error with git clone installation

### ISSUE THREAD

**Issue by theskyisthelimit** [spitzlbergerj/MMM-TeslaLogger#5]
Hello!

If I install the TeslaLogger as described [here](https://github.com/spitzlbergerj/MMM-TeslaLogger#installation) it will not work. In Google Chrome I can see that it tries to call http://XXX.XXX.XXX.XXX:8585/modules/MMM-TeslaLogger//MMM-TeslaLogger.js

`Cannot GET /modules/MMM-TeslaLogger//MMM-TeslaLogger.js`

My workaround is to download the zip from github, extract and execute npm install.

Is this just me?

**Comment by spitzlbergerj** [comment]
I was able to reproduce the error on my computer, but could not (yet) fix it. I am working on it.

**Comment by spitzlbergerj** [comment]
There was an error in the installation instructions. It was written..:

```
git clone https://github.com/spitzlbergerj/MMM-Teslalogger
cd MMM-Teslalogger
npm install
```

But it must be (with capital L)

```
git clone https://github.com/spitzlbergerj/MMM-TeslaLogger
cd MMM-TeslaLogger
npm install

```

**Comment by theskyisthelimit** [comment]
works perfectly now. Thank you!
