### ISSUE TITLE
Timeformat (last updated)

### ISSUE THREAD

**Issue by theskyisthelimit** [spitzlbergerj/MMM-TeslaLogger#8]
The date and time of the last message (Stand auf deutsch) is displayed at the bottom of the module. Somehow on my display the time is displayed as 3:51 instead of 15:51. Can this be configured somewhere?

In the config.js I use 
```
  language: "de",
  timeFormat: 24,
  units: "metric",
```

**Comment by spitzlbergerj** [comment]
Please try 
`localeStr: 'de-DE',`
Probably this should correct this

**Comment by theskyisthelimit** [comment]
It was already set like that. Is it correct that this value should show  the value of the parameter teslamate/cars/1/since ? Maybe the teslamate format is causing the trouble? The value I am seeing now with MQTT Explorer is `2020-03-29T12:54:14.405132Z` for teslamate/cars/1/since

**Comment by spitzlbergerj** [comment]
no, the date is generated as timestamp itself when receiving the MQTT telegram. The time shown is therefore the time of the last reception of an MQTT message

**Comment by spitzlbergerj** [comment]
it ist generated like this
```
var now = Date.now();
var nowStr = self.formatDateTime(now/1000);
```
I'll have a look in this ...

**Comment by spitzlbergerj** [comment]
The time specification is formatted via toLocaleTimeString(). I have now explicitly added the localeString there. Please test.
It worked for me before

**Comment by theskyisthelimit** [comment]
It was still the same after the git pull but after restarting the magic mirror docker container I get 16:30 which is 1 hour off?
